Repository qiboteam/qibolab, pull requests merged in 2022-12, with the labels that each got.

#240 Include pyvisa-py library in qibolab dependencies [tiiq]
  setup.py
Labels: enhancement

#161 Initial support for binning
  .github/workflows/rules.yml
  examples/fidelity_example.py
  src/qibolab/instruments/qblox.py
  src/qibolab/platform.py
  src/qibolab/platforms/multiqubit.py
  src/qibolab/pulses.py
  src/qibolab/runcards/qw5q_gold.yml
  src/qibolab/runcards/tii5q.yml
  src/qibolab/tests/conftest.py
  src/qibolab/tests/test_platforms_multiqubit.yml
Labels: urgent

#247 Single shot measurements for circuits
  src/qibolab/backends.py
  src/qibolab/platforms/abstract.py
  src/qibolab/runcards/tii5q.yml
  src/qibolab/tests/test_backends.py
  src/qibolab/tests/test_platforms_abstract.py
  src/qibolab/tests/test_pulses.py
  src/qibolab/tests/test_transpilers_connectivity.py
  src/qibolab/transpilers/connectivity.py
  src/qibolab/transpilers/native.py
  src/qibolab/transpilers/transpile.py
Labels: urgent

#225 Add workflows for multiple OS and python versions
  .github/workflows/deploy.yml
  .github/workflows/rules.yml
Labels: documentation

#238 first implementation of decomposition into iSWAP or CZ gates
  src/qibolab/platforms/abstract.py
  src/qibolab/tests/test_transpilers_connectivity.py
  src/qibolab/tests/test_transpilers_gate_decompositions.py
  src/qibolab/tests/test_transpilers_native.py
  src/qibolab/tests/test_transpilers_transpile.py
  src/qibolab/tests/test_transpilers_unitary_decompositions.py
  src/qibolab/transpilers/gate_decompositions.py
  src/qibolab/transpilers/native.py
  src/qibolab/transpilers/transpile.py
  src/qibolab/transpilers/unitary_decompositions.py
Labels: transpiler

#252 Temporarily set multiqubit as default platform for multiple runcards
  src/qibolab/platform.py
Labels: platform

#261 New docs font and version display
  doc/source/conf.py
  doc/source/index.rst
Labels: documentation

#263 Rm Ubuntu font from furo configuration
  doc/source/conf.py
Labels: documentation
