Repository qiboteam/qibolab, pull requests merged in 2023-12, with the labels that each got.

#690 Add tests for result shapes
  src/qibolab/instruments/dummy.py
  src/qibolab/instruments/qblox/controller.py
  src/qibolab/instruments/zhinst.py
  tests/test_result_shapes.py
Labels: run-on-qw5q_gold_qblox

#702 Remove Qblox `Cluster`
  src/qibolab/instruments/qblox/cluster.py
  src/qibolab/instruments/qblox/cluster_qcm_bb.py
  src/qibolab/instruments/qblox/cluster_qcm_rf.py
  src/qibolab/instruments/qblox/cluster_qrm_rf.py
  src/qibolab/instruments/qblox/controller.py
  tests/dummy_qrc/qblox.py
  tests/qblox_fixtures.py
  tests/test_instruments_qblox_cluster.py
  tests/test_instruments_qblox_cluster_qcm_bb.py
  tests/test_instruments_qblox_cluster_qcm_rf.py
  tests/test_instruments_qblox_cluster_qrm_rf.py
  tests/test_instruments_qblox_controller.py
Labels: drivers, cleanup

#666 Simplify local oscillator drivers
  src/qibolab/dummy.py
  src/qibolab/instruments/abstract.py
  src/qibolab/instruments/dummy.py
  src/qibolab/instruments/erasynth.py
  src/qibolab/instruments/oscillator.py
  src/qibolab/instruments/rohde_schwarz.py
  src/qibolab/serialize.py
  tests/dummy_qrc/qm.py
  tests/dummy_qrc/zurich.py
  tests/dummy_qrc/zurich.yml
  tests/test_instruments_oscillator.py
  tests/test_instruments_rohde_schwarz.py
Labels: drivers, cleanup

#713 Drop `self._device_parameters` Qblox
  src/qibolab/instruments/qblox/cluster_qcm_bb.py
  src/qibolab/instruments/qblox/cluster_qcm_rf.py
  src/qibolab/instruments/qblox/cluster_qrm_rf.py
  src/qibolab/instruments/qblox/port.py
Labels: drivers, cleanup

#729 Drop `pulse._if` dependence in Qblox
  src/qibolab/instruments/qblox/controller.py
Labels: cleanup
