Repository qiboteam/qibolab, pull requests merged in 2023-10, with the labels that each got.

#601 Blocks decomposition
  src/qibolab/transpilers/blocks.py
  src/qibolab/transpilers/router.py
  tests/test_transpilers_blocks.py
Labels: enhancement, ready for review

#611 Set platform-variable in windows
  doc/source/getting-started/experiment.rst
Labels: documentation

#613 Add fidelity to qubit and fix typo
  src/qibolab/dummy.yml
  src/qibolab/qubits.py
Labels: bug

#617 Add missing RX12 pulse to dummy
  src/qibolab/dummy.yml
Labels: bug

#619 Added tests for custom pulses (#595)
  src/qibolab/pulses.py
  tests/test_pulses.py
Labels: tests

#608 Sabre
  src/qibolab/transpilers/blocks.py
  src/qibolab/transpilers/pipeline.py
  src/qibolab/transpilers/placer.py
  src/qibolab/transpilers/router.py
  tests/test_transpilers_blocks.py
  tests/test_transpilers_pipeline.py
  tests/test_transpilers_placer.py
  tests/test_transpilers_router.py
  tests/test_transpilers_star_connectivity.py
Labels: transpiler, ready for review
