Repository qiboteam/qibolab, pull requests merged in 2023-03, with the labels that each got.

#295 Tests using QM simulator
  src/qibolab/backends.py
  src/qibolab/instruments/qm.py
  tests/conftest.py
  tests/test_instruments_qmsim.py
Labels: enhancement

#319 Improvements to QM driver
  src/qibolab/instruments/qm.py
  src/qibolab/instruments/qmsim.py
  src/qibolab/instruments/rohde_schwarz.py
  tests/conftest.py
  tests/test_instruments_qm.py
  tests/test_instruments_qmsim.py
Labels: enhancement, drivers, run-on-qw5q_gold

#320 Fixing bug related to multiplex
  src/qibolab/platforms/abstract.py
  src/qibolab/platforms/multiqubit.py
  src/qibolab/runcards/qili1q_os2.yml
  src/qibolab/runcards/qw5q_gold.yml
Labels: bug

#276 General connectivity transpiler
  setup.py
  src/qibolab/platform.py
  src/qibolab/transpilers/general_connectivity.py
  tests/test_transpilers_general.py
Labels: transpiler

#326 Add multiqubit dummy platform
  src/qibolab/platform.py
  src/qibolab/runcards/dummy.yml
Labels: enhancement

#332 Bug fix in qblox multiqubit platform affecting multiplexed readout
  src/qibolab/platforms/multiqubit.py
Labels: bug, urgent

#334 Add support for biasing qubits with qblox qcm offsets
  src/qibolab/platforms/multiqubit.py
Labels: enhancement

#347 Update qblox-instruments to version 0.9.0
  setup.py
  src/qibolab/instruments/qblox.py
  src/qibolab/platforms/multiqubit.py
  tests/test_instruments_qblox.py
Labels: enhancement

#353 exclude read-only parameter sequence
  src/qibolab/instruments/qblox.py
Labels: bug, urgent

#345 Implement `Channel.max_bias` and other small fixes
  poetry.lock
  pyproject.toml
  src/qibolab/designs/channels.py
  src/qibolab/instruments/qm.py
  src/qibolab/platform.py
  tests/test_designs_channels.py
  tests/test_instruments_qm.py
Labels: bug, enhancement, drivers
