Repository qiboteam/qibolab, pull requests merged in 2023-04, with the labels that each got.

#364 Fix identity decomposition
  src/qibolab/transpilers/gate_decompositions.py
  tests/test_transpilers_gate_decompositions.py
Labels: transpiler

#355 qw5q_gold runcard as of 20230331 12:00
  src/qibolab/runcards/qw5q_gold_qblox.yml
Labels: urgent, runcard

#317 Driver for RFSoC (qibolab via server)
  doc/source/api-reference/qibolab.rst
  src/qibolab/instruments/rfsoc.py
  src/qibolab/platform.py
  src/qibolab/pulses.py
  src/qibolab/runcards/tii1q_b1.yml
  tests/test_instruments_rfsoc.py
Labels: drivers

#369 Fixes for Qblox driver
  src/qibolab/platforms/multiqubit.py
Labels: bug

#346 Fix behavior of `sweep` method
  src/qibolab/instruments/dummy.py
  src/qibolab/instruments/qm.py
  src/qibolab/instruments/qmsim.py
  src/qibolab/instruments/rfsoc.py
  src/qibolab/platforms/multiqubit.py
  src/qibolab/result.py
  tests/test_instruments_rfsoc.py
  tests/test_result.py
Labels: bug, enhancement

#376 Intregrating Erasynth LO control in the driver
  src/qibolab/instruments/rfsoc.py
  src/qibolab/platform.py
Labels: enhancement, drivers

#381 Correct classification parameters in runcard
  src/qibolab/runcards/qw5q_gold_qblox.yml
Labels: runcard

#384 Fix self-runner
  .github/workflows/selfhosted.yml
  qputests.sh
Labels: run-on-tii1q_b1

#348 Transpiler V2
  src/qibolab/platforms/abstract.py
  src/qibolab/transpilers/gate_decompositions.py
  src/qibolab/transpilers/general_connectivity.py
  src/qibolab/transpilers/transpile.py
  tests/test_transpilers_gate_decompositions.py
  tests/test_transpilers_general.py
  tests/test_transpilers_transpile.py
Labels: transpiler

#390 Raise error on self-runner test
  qputests.sh
Labels: run-on-tii1q_b1

#386 Exposing TWPA parameters for abstract and multiqubit
  src/qibolab/platforms/abstract.py
  src/qibolab/platforms/multiqubit.py
  src/qibolab/platforms/platform.py
Labels: enhancement, urgent
