Repository qiboteam/qibolab, pull requests merged in 2023-06, with the labels that each got.

#373 ZCU111
  doc/source/api-reference/qibolab.rst
  poetry.lock
  pyproject.toml
  src/qibolab/instruments/rfsoc.py
  tests/dummy_qrc/rfsoc.py
  tests/test_instruments_rfsoc.py
Labels: drivers

#461 David/qblox exec params
  src/qibolab/instruments/qblox.py
  src/qibolab/platforms/multiqubit.py
Labels: enhancement, drivers

#490 Backprop placer
  src/qibolab/transpilers/abstract.py
  src/qibolab/transpilers/placer.py
  src/qibolab/transpilers/routing.py
  tests/test_transpilers_abstract.py
  tests/test_transpilers_placer.py
Labels: transpiler

#499 Reshaping sweeping results for `dummy`
  src/qibolab/instruments/dummy.py
  tests/test_platforms_dummy.py
Labels: bug

#474 Time sweepers rfsoc
  poetry.lock
  pyproject.toml
  src/qibolab/instruments/rfsoc.py
  src/qibolab/sweeper.py
  tests/test_instruments_rfsoc.py
Labels: drivers, deploy on hardware
