Repository qiboteam/qibolab, pull requests merged in 2023-11, with the labels that each got.

#644 Update lock and bug fix
  poetry.lock
  pyproject.toml
  src/qibolab/platform.py
Labels: bug, urgent

#655 Fix problems with RFSoC driver after adding couplers
  src/qibolab/instruments/rfsoc/driver.py
Labels: bug

#659 Fix Rabi probability qblox
  src/qibolab/instruments/qblox/controller.py
Labels: bug, urgent

#640 Simplify and move Qblox modules settings
  src/qibolab/instruments/qblox/cluster_qcm_bb.py
  src/qibolab/instruments/qblox/cluster_qcm_rf.py
  src/qibolab/instruments/qblox/cluster_qrm_rf.py
  src/qibolab/instruments/qblox/controller.py
  src/qibolab/instruments/qblox/port.py
  src/qibolab/serialize.py
  tests/dummy_qrc/qblox.py
  tests/dummy_qrc/qblox.yml
  tests/qblox_fixtures.py
  tests/test_instruments_qblox_cluster_qcm_bb.py
  tests/test_instruments_qblox_cluster_qcm_rf.py
  tests/test_instruments_qblox_cluster_qrm_rf.py
Labels: enhancement, drivers
