Repository qiboteam/qibolab, pull requests merged in 2023-05, with the labels that each got.

#397 Fix ERA test
  tests/conftest.py
  tests/test_instruments_erasynth.py
Labels: run-on-tii1q_b1

#350 Fix Pulse performance issues caused by SymbolicExpressions, closes #323
  src/qibolab/pulses.py
  src/qibolab/symbolic.py
  tests/test_pulses.py
Labels: bug, enhancement

#399 David/reload settings qblox sweepers
  .pre-commit-config.yaml
  src/qibolab/instruments/dummy.py
  src/qibolab/instruments/erasynth.py
  src/qibolab/instruments/qm.py
  src/qibolab/instruments/rfsoc.py
  src/qibolab/platform.py
  src/qibolab/platforms/abstract.py
  src/qibolab/platforms/multiqubit.py
  src/qibolab/platforms/platform.py
  src/qibolab/pulses.py
  src/qibolab/runcards/dummy.yml
  src/qibolab/runcards/qw5q_gold_qblox.yml
  src/qibolab/runcards/tii1q_b1.yml
  src/qibolab/sweeper.py
  src/qibolab/symbolic.py
  src/qibolab/transpilers/gate_decompositions.py
  src/qibolab/transpilers/general_connectivity.py
  src/qibolab/transpilers/transpile.py
  tests/test_instruments_qm.py
  tests/test_instruments_qmsim.py
  tests/test_pulses.py
  tests/test_transpilers_gate_decompositions.py
  tests/test_transpilers_general.py
  tests/test_transpilers_transpile.py
Labels: enhancement, do not merge, calibration

#379 Re-calibration tii1q_b1
  .github/workflows/selfhosted.yml
  qputests.sh
  src/qibolab/designs/channels.py
  src/qibolab/instruments/rfsoc.py
  src/qibolab/platforms/platform.py
  src/qibolab/runcards/tii1q_b1.yml
  tests/conftest.py
  tests/test_designs_channels.py
  tests/test_instruments_rfsoc.py
  tests/test_platforms.py
Labels: runcard, run-on-tii1q_b1

#404 Rfosc ExecutionParameters, New Results
  src/qibolab/instruments/rfsoc.py
  src/qibolab/platforms/platform.py
Labels: drivers

#411 Add TWPA to RFSoc4x2
  src/qibolab/platform.py
  src/qibolab/runcards/tii1q_b1.yml
Labels: run-on-tii1q_b1

#415 Maxime/iqm
  src/qibolab/instruments/zhinst.py
Labels: do not merge

#409 Use shared selfhosted workflow
  .github/workflows/selfhosted.yml
  selfhosted
Labels: tests, run-on-tii1q_b1

#400 ExecutionParameters, AveragingType, AcquisitionMode
  src/qibolab/__init__.py
  src/qibolab/backends.py
  src/qibolab/instruments/dummy.py
  src/qibolab/instruments/qm.py
  src/qibolab/instruments/qmsim.py
  src/qibolab/instruments/rfsoc.py
  src/qibolab/platforms/abstract.py
  src/qibolab/platforms/icplatform.py
  src/qibolab/platforms/multiqubit.py
  src/qibolab/platforms/platform.py
  src/qibolab/result.py
  src/qibolab/runcards/dummy.yml
  src/qibolab/runcards/multiqubit_icarusq.yml
  src/qibolab/runcards/multiqubit_icarusqfpga.yml
  src/qibolab/runcards/qili1q_os2.yml
  src/qibolab/runcards/qw5q_gold.yml
  src/qibolab/runcards/qw5q_gold_qblox.yml
  src/qibolab/runcards/tii1q_b1.yml
  src/qibolab/sweeper.py
  tests/test_instruments_qm.py
  tests/test_instruments_qmsim.py
  tests/test_instruments_rfsoc.py
  tests/test_platforms_dummy.py
  tests/test_result.py
Labels: enhancement, drivers

#450 fix
  src/qibolab/instruments/rfsoc.py
  src/qibolab/result.py
  tests/test_instruments_rfsoc.py
  tests/test_platforms_abstract.py
  tests/test_result.py
Labels: run-on-tii1q_b1

#222 Zurich instruments
  .github/workflows/deploy.yml
  .github/workflows/rules.yml
  poetry.lock
  pyproject.toml
  src/qibolab/designs/channels.py
  src/qibolab/instruments/dummy_oscillator.py
  src/qibolab/instruments/zhinst.py
  src/qibolab/platform.py
  src/qibolab/platforms/abstract.py
  src/qibolab/pulses.py
  src/qibolab/runcards/iqm5q.yml
  tests/test_backends.py
  tests/test_instruments_zhinst.py
Labels: drivers, run-on-iqm5q

#447 `tii1q_b1` recalibration after reboot
  src/qibolab/runcards/tii1q_b1.yml
Labels: run-on-tii1q_b1, recalibration
